sonar.projectKey=Todo_Application
sonar.projectName=Todo_Application
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqp_2067bdc2cb078ecd4e9506094b867754ccf52491