name: Build and Push

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: todo-ui
      IMAGE_TAG: v4
      ACR_NAME: todoappacr001
      ACR_LOGIN_SERVER: todoappacr001.azurecr.io
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:           
          client-id: "089d4a75-538e-41d9-9751-59817b989f35"
          tenant-id: "5bb66004-782c-4c37-9c7d-578c7714c94f"
          subscription-id: "0fed9206-7606-41d6-bea8-83033d2b432f"

      - name: Log in to Azure Container Regostry
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: | 
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          
      - name: Push Docker Image to ACR
        run: | 
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
